[versions]
javaTarget = "25"
dynmap = "3.8"
paper = "26.2.build.+"
bukkit = "26.1.2-R0.1-SNAPSHOT"
worldedit = "7.4.5"
worldguard = "7.0.0"
squirrelid = "0.2.0"
shadow = "9.6.1"

[libraries]
dynmap-api = { group = "us.dynmap", name = "dynmap-api", version.ref = "dynmap" }
dynmap-core-api = { group = "us.dynmap", name = "DynmapCoreAPI", version.ref = "dynmap" }
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
bukkit = { group = "org.bukkit", name = "bukkit", version.ref = "bukkit" }
worldedit-bukkit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldedit" }
worldguard-bukkit = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard" }
squirrelid = { group = "com.sk89q", name = "squirrelid", version.ref = "squirrelid" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
